<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYylhBGv\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYylhBGv/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYylhBGv.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYylhBGv\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYylhBGv\appAppKernelProdContainer([
    'container.build_hash' => 'YylhBGv',
    'container.build_id' => '2d921015',
    'container.build_time' => 1686443663,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYylhBGv');
